-   id: assumptions
    name: Document project assumptions and caveats
    description: This hook generates documentation from hashed code comments
    entry: assumptions
    language: python
    language_version: python3
    always_run: true
    pass_filenames: false
    files: ^(\.pre-commit-hooks\.yaml|hooks\.yaml)$
